/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p1_hazielpavon;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Operaciones = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Numeros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        Operaciones.setText("Operaciones");

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });

        Numeros.setText("Numeros");
        Numeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumerosMouseClicked(evt);
            }
        });

        jLabel1.setText("Examen ||");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salir)
                            .addComponent(Numeros)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Operaciones)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Numeros)
                .addGap(38, 38, 38)
                .addComponent(Operaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static ArrayList<Numero> listar = new ArrayList<>();
    static Numero n = new Numero();

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void NumerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumerosMouseClicked

        boolean seguir = true;
        boolean vali2 = false;

        while (seguir == true) {

            int opcion = Integer.parseInt(JOptionPane.showInputDialog(null, " "
                    + "1. Agregar Numeros\n"
                    + "2. Eliminar Numeros\n"
                    + "3. Menu Principal\n"
            ));
            int respu = 0;
            int z = 0;
            int respu2 = 0;
            switch (opcion) {

                case 1:

                    boolean vali = false;

                    while (vali == false) {
                        String decimal = JOptionPane.showInputDialog(null, " Ingrese el numero decimal: ");

                        int base = Integer.parseInt(JOptionPane.showInputDialog(null, " Ingrese la base: "));

                        int dec = Integer.parseInt(decimal);

                        if (base <= 35 && base >= 2 && dec > 1) {
                            vali = true;
                            n.setBase(base);
                            n.setNum(dec);

                            for (int i = decimal.length()-1 ; i >= 0; i--) {
                                String x = "";
                                x += decimal.charAt(i);

                                z += Integer.parseInt(x);

                                if (z != 0) {
                                    respu += z * (Math.pow(base, i));
                                } else {
                                    respu += 0;
                                }
                                
                            }
                            n.setResp(respu);
                            Numero n = new Numero(base, dec, respu);
                            listar.add(n);

                        } else {

                            JOptionPane.showMessageDialog(null, " Ingrese un numero mayor a 2 de base y menor que 35 y un numero mayor a 1 como decimal ");

                        }
                    }

                    vali2 = true;
                    break;

                case 2:

                    if (vali2 == false) {

                        JOptionPane.showMessageDialog(null, "Ingrese un numero a la lista antes de eliminarlos");
                    } else {
                        JOptionPane.showMessageDialog(null, print());

                        String pos = (JOptionPane.showInputDialog(null, "Ingrese el indice del numero que desee ingresar"));
                    }
                    break;

                case 3:
                    seguir = false;

                    break;

            }

        }

    }//GEN-LAST:event_NumerosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    public static String print() {

        String list = "";
        int cont = 1;

        for (int i = 0; i < listar.size(); i++) {
            list += cont++ + ". ";

            list += (listar.get(i).toString());

            list += "\n";
        }

        return list;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Numeros;
    private javax.swing.JButton Operaciones;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
